### ISSUE TITLE
Bug: unable to use with android-x preference library

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [jaredrummler/ColorPicker#65]
All classes here extend from `android.preference.Preference` instead of from `androidx.preference.Preference` , while using this in gradle file:

    implementation 'androidx.preference:preference:1.0.0'

This means that if I use this repository within a class that extends PreferenceFragmentCompat, I get a crash of this sort:

```
    android.view.InflateException: Binary XML file line #15: Error inflating class com.jaredrummler.android.colorpicker.ColorPreference
        at androidx.preference.PreferenceInflater.createItem(PreferenceInflater.java:266)
        at androidx.preference.PreferenceInflater.createItemFromTag(PreferenceInflater.java:295)
        at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:362)
        at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:170)
        at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:120)
        at androidx.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:138)
        at androidx.preference.PreferenceFragmentCompat.setPreferencesFromResource(PreferenceFragmentCompat.java:445)
```

Please fix this. This is the only reason I've forked this repository into mine:

https://github.com/AndroidDeveloperLB/ColorPicker

**Comment by AndroidDeveloperLB** [comment]
Oh I think I'm supposed to use this now:

 com.jaredrummler.android.colorpicker.ColorPreferenceCompat 

right?

**Comment by AndroidDeveloperLB** [comment]
Oh I think I'm supposed to use this now:

com.jaredrummler.android.colorpicker.ColorPreferenceCompat

right?

**Comment by SapuSeven** [comment]
Worked for me after switching to `com.jaredrummler.android.colorpicker.ColorPreferenceCompat`.

This should be mentioned in the README.

**Comment by jaredrummler** [comment]
Updated README and now the library includes AndroidX
